"""added stock_exchange

Revision ID: cde4e49075a6
Revises: c5e3ed9a82a7
Create Date: 2026-09-10 11:42:51.786799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cde4e49075a6'
down_revision: Union[str, Sequence[str], None] = 'c5e3ed9a82a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('stock_exchange', sa.String(length=6), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'stock_exchange')
    # ### end Alembic commands ###
